# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wp-onboarding

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://wp-onboarding.azurewebsites.net/
        username: ${{ secrets.AzureAppService_ContainerUsername_7330a5d523f441558c1d7294c5582c7d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_228727f78d2c4e788cb579c95f26a1fb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wp-onboarding.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_7330a5d523f441558c1d7294c5582c7d }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wp-onboarding'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f151cc2d0fc641118d8d9a2c951923eb }}
        images: 'wp-onboarding.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_7330a5d523f441558c1d7294c5582c7d }}/appsvc/wordpress-alpine-php:${{ github.sha }}'